volumes:
  rsyncd:
    external: true
    
services:
  rsyncd:
    # Uncomment one of these. Use :latest if you want the stable build, use :dev if you want the development build
    image: iainbullock/rsyncd:latest
    #image: iainbullock/rsyncd:dev
    container_name: rsyncd
   
    volumes:
      - rsyncd:/config
      # Change to the root where all your modules are located. Could be /
      - /home:/home
    
    network_mode: bridge
    ports:
      - 10873:873
         
    # Allow opening of a shell in container
    tty: true
    stdin_open: true    
    # Uncomment if you need a container shell when the container won't run 
    #entrypoint: "/bin/ash"
    
    restart: unless-stopped
    stop_grace_period: 2m